### PR TITLE
Hyperion

### PR DESCRIPTION
**Pull request by yshinozu**
Hi David and Phil, 

The requested changes, all in apply_oe.py, will enable Hyperion processing. Thank you for considering.

Yohei

### CODE REVIEW

**Comment by davidraythompson** [comment]
This looks good, thank you! 
I believe your ISOFIT_DATA_DIR environment variable is intended to point to the top-level ISOFIT installation location? If so, how about we call it ISOFIT_DIR to avoid confusion with our data subdirectory?

**Comment by yshinozu** [comment]
Hi David and Phil,

First of all thank you for patiently guiding me to this stage. I now have an operational script to run Hyperion scenes. I will continue to examine the results in relation to the input spectra, calibration, wavelength overlap, geographical assignment, etc.

On the directory name, that is fine. I picked "data" because there is only one directory with that name; isofit appears twice (isofit/isofit/). But we should be able to point to the correct level. Thank you for checking with me on this.

Yohei

--
Shinozuka, Yohei    ***@***.***
Bay Area Environmental Research Institute
NASA Ames Research Center, MS 245-5
Moffett Field, CA 94035

________________________________________
From: David R Thompson ***@***.***>
Sent: Wednesday, May 12, 2021 9:22 AM
To: isofit/isofit
Cc: Shinozuka, Yohei (ARC-SGG)[Bay Area Environmental Research Institute]; Author
Subject: [EXTERNAL] Re: [isofit/isofit] Hyperion (#229)

This looks good, thank you!
I believe your ISOFIT_DATA_DIR environment variable is intended to point to the top-level ISOFIT installation location? If so, how about we call it ISOFIT_DIR to avoid confusion with our data subdirectory?

**Comment by pgbrodrick** [comment]
Hi Yohei,

These changes look great, thanks for integrating them in!  I changed the directory reference to ISOFIT_DIR per David's rec, which I tend to agree with.  You would now set the ISOFIT_IDR variable to the top-level isofit repo, e.g.:

ISOFIT_DIR = '/Users/brodrick/repos/isofit'

If you're okay with that change, I'll merge this in!

**Comment by yshinozu** [comment]
Great! Thank you for incorporating them.

Yohei

--
Shinozuka, Yohei    ***@***.***
Bay Area Environmental Research Institute
NASA Ames Research Center, MS 245-5
Moffett Field, CA 94035

________________________________________
From: Phil Brodrick ***@***.***>
Sent: Thursday, May 13, 2021 5:07 PM
To: isofit/isofit
Cc: Shinozuka, Yohei (ARC-SGG)[Bay Area Environmental Research Institute]; Author
Subject: [EXTERNAL] Re: [isofit/isofit] Hyperion (#229)

Hi Yohei,

These changes look great, thanks for integrating them in! I changed the directory reference to ISOFIT_DIR per David's rec, which I tend to agree with. You would now set the ISOFIT_IDR variable to the top-level isofit repo, e.g.:

ISOFIT_DIR = '/Users/brodrick/repos/isofit'

If you're okay with that change, I'll merge this in!

**Pull request merged**
