### PR TITLE
Add the handling of flux quantities #2.

### PR DESCRIPTION
**Pull request by unbohn**
Rebases #481 onto `dev`.

### CODE REVIEW

**Comment by unbohn** [comment]
@pgbrodrick @jammont This PR is now a clean rebase of #481 onto `dev` with a clear overview of the introduced changes. Sorry for the confusion, I should be more careful with merging base branches into PR branches. That would actually follow Kevin's suggestion.

**Comment by unbohn** [comment]
@pgbrodrick Good idea! Duly added. In this case, I think we don't need the general `rt_mode` check in the RadiativeTransferEngine `init` anymore. It's only required when loading the information from a prebuilt LUT file.

**Comment by pgbrodrick** [comment]
Thanks for that update - looks good to me.  @jammont, on to you for a quick review.

**Review by jammont — APPROVED** [review]
Looks good to me 👍

**Pull request merged**
