### PR TITLE
Utilsfix

### PR DESCRIPTION
**Pull request by adam-erickson**
This pull request provides the following changes:

- House cleaning of the import order so that local files are imported after
- Internalizing of package utilities into `utils.py` file/submodule.
- Merging of all tests to internal `test` submodule. All tests must pass for CI to pass.
- Addition of `Isofit` and `Sunposition` classes for non-CLI use, useful for example in creating cross-platform example scripts; the former has a `run()` method for separating out initialization. The nice thing is that these objects store the model inputs and outputs for subsequent analysis.
- Addition of cross-platform Python example scripts
- Removal of unused imports - more likely remain
- Removal of the `utils` and `tests` folder in the base directory

Let me know your thoughts after testing this on your end and feel free to veto. Basically, the idea here is to offer both internal and external methods for isofit and sunposition, while further internalizing all utilities and tests.

### CODE REVIEW

**Comment by adam-erickson** [comment]
I'll fix this in one moment...

**Comment by winstonolson** [comment]
No worries.  I have some commitments today and the earliest I will get a chance to look at these updates is tomorrow.

**Comment by winstonolson** [comment]
I've had a chance to checkout these changes and try them out. I created a branch called "release-1.2.0" that contains the updates from this pull request along with some tweaks I had to make to get the examples to run successfully.  Nothing major, just a couple places that the code refactoring missed.

I'm still having issues with the libradtran example, but I think it's a separate issue that can be resolved later.

@davidraythompson, I'd like to increment the version to 1.2.0 in light of all the recent changes, both Adam's structural changes and your new fast segmentation.  The version history has been updated here: https://github.com/isofit/isofit/wiki/Release-Notes#version-history

@adam-erickson, I still have an order of operations question regarding the sha256 value in meta.yaml.  If I use the Github releases GUI to create the release and the release archive then the sha256 value which is currently checked in becomes obsolete.  Do you then update this file afterwards on the master branch with the new sha256 value?  If so, I might need to change our Pypi deploy so that it's no longer automatic.

**Comment by adam-erickson** [comment]
@winstonolson If I understand your question correctly, each new release should have a new SHA256 value, which must be updated on the conda recipe to build correctly. You can download the release to a local folder and run (on MacOS) `openssl dgst -sha256 thefilename`. This is equivalent to `sha256sum` on Linux.

**Comment by davidraythompson** [comment]
Looks good. I second the motion to merge 1.2.0 into master
David

Sent from my phone

On Oct 24, 2019, at 13:53, winstonolson <notifications@github.com> wrote:

﻿

I've had a chance to checkout these changes and try them out. I created a branch called "release-1.2.0" that contains the updates from this pull request along with some tweaks I had to make to get the examples to run successfully. Nothing major, just a couple places that the code refactoring missed.

I'm still having issues with the libradtran example, but I think it's a separate issue that can be resolved later.

@davidraythompson<https://github.com/davidraythompson>, I'd like to increment the version to 1.2.0 in light of all the recent changes, both Adam's structural changes and your new fast segmentation. The version history has been updated here: https://github.com/isofit/isofit/wiki/Release-Notes#version-history

@adam-erickson<https://github.com/adam-erickson>, I still have an order of operations question regarding the sha256 value in meta.yaml. If I use the Github releases GUI to create the release and the release archive then the sha256 value which is currently checked in becomes obsolete. Do you then update this file afterwards on the master branch with the new sha256 value? If so, I might need to change our Pypi deploy so that it's no longer automatic.

**Comment by winstonolson** [comment]
Just a few final notes.  The reason I've been asking about the sha256 value is that we have been using Travis CI to automatically deploy to Pypi whenever master is updated with a new release version.  

In addition, Pypi will only accept a new uploaded version once.  Any additional uploads to Pypi with the same version number will error out, even if you delete the previous version on Pypi.  So committing a new change to the meta.yaml file to include the new sha256 value after Pypi has already been updated causes some issues with our current release process.

However, this is a minor detail and we can figure out a new release process for Pypi and conda-forge in the near future (perhaps using Pypi as the source for the conda-forge recipe as you mentioned).  For this particular release, I am removing the automatic deployment to Pypi from .travis.yml until we settle on a new process.  I will create a release on https://github.com/isofit/isofit/releases, update the meta.yaml file with the new sha256 value, and then deploy to Pypi.

Also, I have included a new requirement for "scikit-image".  It looks like this is now needed to import "slic" from skimage.segmentation.  I've added this requirement to setup.py and meta.yaml.

And finally, I have updated the README and CONTRIBUTING docs to reflect recent changes.  I will update master shortly with these latest changes.

**Pull request merged**
