### PR TITLE
patch fix to read loc data

### PR DESCRIPTION
**Pull request by pgbrodrick**
Addresses: #430.  @davidraythompson, for review.

### CODE REVIEW

**Comment by pgbrodrick** [comment]
Current failures are due to avng server being down.  Will rerun once stood back up (should be 01/16/2024).  Patch is likely acceptable in the interim, however.

**Comment by davidraythompson** [comment]
I think the code below the change assumes BSQ layout.   But it worked after I made the change:
1349   loc_data = loc_dataset.open_memmap(interleave="bsq", writable=False)

**Comment by davidraythompson** [comment]
If this looks okay I'm fine with merging it.

**Comment by pgbrodrick** [comment]
Good catch, the rest of the function inferred GDAL read order.  This should work fine, merge away.

**Pull request merged**
