### PR TITLE
Added two SLURM examples and other small changes

### PR DESCRIPTION
**Pull request by serbinsh**
Updated workflow.py to provide a text file of the different simulation experiments. Provided prepare_example_hypertrace_data.sh to make it easier to obtain the example datasets, noise, and surface files.

### CODE REVIEW

**Comment by pgbrodrick** [comment]
Looks good in general.  The SLURM implementation for ray looks like it's still set up for runs with 0.8.5 though, and will likely fail with 1.+ (or at least does on the systems I use).  There's a working example in the ray update PR: https://github.com/isofit/isofit/pull/210.  The adjustments are small, just flags for the ray start call.

**Comment by serbinsh** [comment]
Ahh, thanks @pgbrodrick!  This is really helpful.  Indeed it did run but I can see how if it had spawned to node02 it would have failed. thanks for sharing your example changes! I will mirror those and retest

**Comment by serbinsh** [comment]
So updated the examples.  Still working OK but also still getting the cryptic error message:

```
/data2/sserbin/conda_envs/isofit_develop/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1391: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
Simulations sorted by RMSE (lowest first)
                                           directory  ...  rel_bias
0  output-libradtran/atm_midlatitude_winter__szen...  ...  0.000278

[1 rows x 19 columns]

Run completed on:  Fri Mar 5 12:12:01 EST 2021
srun: Job step aborted: Waiting up to 32 seconds for job step to finish.
srun: Job step aborted: Waiting up to 32 seconds for job step to finish.
slurmstepd: error: *** STEP 285.7 ON node01 CANCELLED AT 2021-03-05T12:12:01 ***
slurmstepd: error: *** STEP 285.8 ON node02 CANCELLED AT 2021-03-05T12:12:01 ***
2021-03-05 11:57:14,579	INFO scripts.py:643 -- Local node IP: 10.16.1.2
2021-03-05 11:57:14,617	SUCC scripts.py:656 -- --------------------
2021-03-05 11:57:14,617	SUCC scripts.py:657 -- Ray runtime started.
2021-03-05 11:57:14,618	SUCC scripts.py:658 -- --------------------
2021-03-05 11:57:14,618	INFO scripts.py:660 -- To terminate the Ray runtime, run
2021-03-05 11:57:14,618	INFO scripts.py:661 --   ray stop
2021-03-05 11:57:14,618	INFO scripts.py:665 -- --block
2021-03-05 11:57:14,618	INFO scripts.py:666 -- This command will now block until terminated by a signal.
2021-03-05 11:57:14,618	INFO scripts.py:668 -- Running subprocesses are monitored and a message will be printed if any of them terminate unexpectedly.
srun: error: node02: task 0: Exited with exit code 1
2021-03-05 11:57:12,569	INFO scripts.py:537 -- Local node IP: 10.16.1.1
2021-03-05 11:57:13,070	SUCC scripts.py:565 -- --------------------
2021-03-05 11:57:13,070	SUCC scripts.py:566 -- Ray runtime started.
2021-03-05 11:57:13,070	SUCC scripts.py:567 -- --------------------
2021-03-05 11:57:13,071	INFO scripts.py:569 -- Next steps
2021-03-05 11:57:13,071	INFO scripts.py:570 -- To connect to this Ray runtime from another node, run
2021-03-05 11:57:13,071	INFO scripts.py:574 --   ray start --address='10.16.1.1:6379' --redis-password='d1eda0fc-ccb4-4904-afe8-552d69705e8d'
2021-03-05 11:57:13,071	INFO scripts.py:579 -- Alternatively, use the following Python code:
2021-03-05 11:57:13,072	INFO scripts.py:582 -- import ray
2021-03-05 11:57:13,073	INFO scripts.py:583 -- ray.init(address='auto', _redis_password='d1eda0fc-ccb4-4904-afe8-552d69705e8d')
2021-03-05 11:57:13,073	INFO scripts.py:591 -- If connection fails, check your firewall settings and network configuration.
2021-03-05 11:57:13,073	INFO scripts.py:596 -- To terminate the Ray runtime, run
2021-03-05 11:57:13,073	INFO scripts.py:597 --   ray stop
2021-03-05 11:57:13,073	INFO scripts.py:665 -- --block
2021-03-05 11:57:13,073	INFO scripts.py:666 -- This command will now block until terminated by a signal.
2021-03-05 11:57:13,073	INFO scripts.py:668 -- Running subprocesses are monitored and a message will be printed if any of them terminate unexpectedly.
srun: error: node01: task 0: Exited with exit code 1
```

**Comment by serbinsh** [comment]
not clear why this failed, looks unrelated to code changes

**Comment by pgbrodrick** [comment]
Looks like it was the gdal install, but I don't see exactly why, especially as subsequent PR's passed....rerunning to check.

**Comment by davidraythompson** [comment]
Thanks @serbinsh.
@pgbrodrick, are you satisfied with the ray 1.+ compatibility?

**Comment by pgbrodrick** [comment]
Yup, that should do the trick - thanks for making the update @serbinsh.  Merging.

**Pull request merged**
