### PR TITLE
Surface Model CLI

### PR DESCRIPTION
**Pull request by jammont**
Click implementation for the surface_model.py wasn't working, this fixes it. Changed optional `--` options from `argument` to `option`, and required options removed `--`

Closes #SlackConversation

### CODE REVIEW

**Comment by pgbrodrick** [comment]
@jammont - wavelength_path and output_path should remain optional.  Nominally, the json values are used, and these just overwrite those.  Should those arguments change to keyword 'optional' to allow this?

**Comment by jammont** [comment]
Changed them back to optional:
```bash
$ isofit surface_model --help
Usage: isofit surface_model [OPTIONS] CONFIG_PATH

  Build a new surface model to a block of data

Options:
  --wavelength_path TEXT  Input wavelengths to three-column wavelength file to
                          use
  --output_path TEXT      Path to write the created surface model to
  --seed INTEGER          Seed for reproducibility
  --help                  Show this message and exit.
```

**Comment by unbohn** [comment]
Looks good. Thanks, @jammont!

**Review by unbohn — APPROVED** [review]

**Comment by pgbrodrick** [comment]
Perfect, thanks!

**Pull request merged**
