### PR TITLE
Hashing covariance

### PR DESCRIPTION
**Pull request by NimrodCarmon**
This change will make the hashtable to be used more. The reason it was not used a lot before is that the prior covariances are being scaled by the norm of the reflectance state, which changes within iterations, so the hashing can't match. Now we decoupled the scaling from the inversion, so the hashtable is used more. I banchmarked this and see about 1.5x in performance (spectra/second/core)

### CODE REVIEW

**Comment by davidraythompson** [comment]
Hi @NimrodCarmon - thanks for the PR.  
Note that I'd tried to keep the code inverse.py independent of the particular reflectance model assumptions we make.  Consequently our inversion routine knows that a multivariate prior exists, but it doesn't care about the interpretation of those numbers.    This means that we can change our reflectance model without having to change inverse.py.   For example, some of our current use cases involve models where the reflectance prior is not normalized, or where the reference channels used in the normalization are different  from the state vector, or where the reflectance is a lookup table based on a small number of state vector parameters.  It seems like this would break those other cases?  I might be wrong.  But if so, is there a way that we could confine our changes entirely within the multicomponent surface model?

**Comment by pgbrodrick** [comment]
Let's rerun the profiling to check that this is worth it.  If so, proposed solution:

- Add Sa_inv function to surface.py
- Default Sa_inv:
    - Run Sa
    - do inverse
    - return Sa and Sa_inv
 - multicomponent_surface
    - remove normalization
    - do inverse
    - re-apply normalization
    - return Sa and Sa_inv
  
Question: does the un-normalization modify Sa past the point where the hashing function can catch it?

**Comment by pgbrodrick** [comment]
This can now be addressed thanks to #333 .

**Comment by unbohn** [comment]
Closing this due to an inactive head repository. Continuing in #350.

**Pull request closed without merging**
