### PR TITLE
sRTMnet (hybrid simulator/emulator) integration

### PR DESCRIPTION
**Pull request by pgbrodrick**
This PR brings in the capacity to utilize the sRTMnet radiative transfer procedure, currently in peer-review.  A trained neural network is required, and is available on request (a public link will be made available soon, along with corresponding model training code repository).  This PR comment will be modified with said links as they become available.

Changes include:

- new sRTMnet.py module
- updates to modtran and 6s to support sRTMnet and comparisons with MODTRAN (fully backwards compatible)
- apply_oe.py updates to allow the emulator to be used in a standard workflow

At this point, sRTMnet still requires a 6s installation, though future updates could fold in the corresponding python libraries to not require external installations.

@davidraythompson, could you review at your convenience?

### CODE REVIEW

**Comment by davidraythompson** [comment]
A milestone!  It looks like Travis may not understand the new .travis.yml but otherwise this looks great.  Would you prefer a direct merge or a squash?

**Comment by pgbrodrick** [comment]
Looks like Travis is finally happy. @davidraythompson, I think a squash commit is best for this given the amount of back-and-forth in the development.

**Comment by davidraythompson** [comment]
@pgbrodrick I hope your conversation with Travis stayed civil :)  would you like me to preserve the commit history?

**Comment by davidraythompson** [comment]
Got your comment.  Squashing.

**Pull request merged**
