### PR TITLE
CI/CD Docker

### PR DESCRIPTION
**Pull request by jammont**
<h1>Description</h1>

Refactors the CI/CD files to use the new official Docker image. The image is currently hosted as [jammont/isofit](https://hub.docker.com/repository/docker/jammont/isofit/general) on dockerhub. We can leave this as is temporarily until we have an official isofit account on Dockerhub that joins their open source program.

Additionally, this PR updates the tensorflow package to be installed via pip instead of Conda. It is recommended by the tensorflow documentation to use pip as well as there were sudden issues with the micromamba in the docker container installing isofit. Instead of resolving why it couldn't, we should just follow best practices and install via pip:

> [Note: Do not install TensorFlow with conda. It may not have the latest stable version. pip is recommended since TensorFlow is only officially released to PyPI.](https://www.tensorflow.org/install/pip)

<h1>Changes</h1>

- ✨ New addition
- 🐛 Resolved a bug
- 🗒️ Documentation

<table>
  <tr>
    <th></th>
    <th>Description</th>
  </tr>
  <tr>
    <td>:sparkles:</td>
    <td>Replaced container in example workflows to use new official image</td>
  </tr>
  <tr>
    <td>:sparkles:</td>
    <td>Updated tensorflow to be pip installed in both the conda-environment.yml and Dockerfile</td>
  </tr>
</table>

### CODE REVIEW

**Comment by jammont** [comment]
All of the checks are failing as the currently hosted isofit image only supports linux/arm64 whereas github uses linux/amd64. These should all be passing once the amd64 image is posted. In the meantime, the files are ready for review.

**Comment by unbohn** [comment]
@jammont This looks great! Thanks for implementing this huge step forward. No suggested edits from my side. As you mentioned it above, are you working on getting the amd64 image posted?

**Comment by jammont** [comment]
The git workflows are now working and passing. This is now ready for merge. 

And yes, both AMD64 and ARM64 images are posted at this time. More to come soon.

**Comment by unbohn** [comment]
Thanks, @jammont, this is excellent!

**Review by unbohn — APPROVED** [review]

**Comment by pgbrodrick** [comment]
Looks great.  Thanks James!

**Pull request merged**
