### PR TITLE
Separation of surface state vector indexes.

### LINKED ISSUE #315: Santa Monica example fails
The Santa Monica example raises an exception on [line 306 of inverse.py](https://github.com/isofit/isofit/blob/master/isofit/inversion/inverse.py#L306).

```python
Traceback (most recent call last):
  File "/usr/local/bin/isofit", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/__w/isofit/isofit/bin/isofit", line 52, in <module>
    main()
  File "/__w/isofit/isofit/bin/isofit", line 47, in main
    return isofit.run()
  File "/__w/isofit/isofit/isofit/core/isofit.py", line 164, in run
    res = list(self.workers.map_unordered(lambda a, b: a.run_set_of_spectra.remote(b), indices_to_run))
  File "/usr/local/lib/python3.8/dist-packages/ray/util/actor_pool.py", line 120, in map_unordered
    yield self.get_next_unordered()
  File "/usr/local/lib/python3.8/dist-packages/ray/util/actor_pool.py", line 265, in get_next_unordered
    return ray.get(future)
  File "/usr/local/lib/python3.8/dist-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/ray/_private/worker.py", line 2289, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(IndexError): ray::Worker.run_set_of_spectra() (pid=1363, ip=172.18.0.2, repr=<isofit.core.isofit.Worker object at 0x7fe5f4190820>)
  File "/__w/isofit/isofit/isofit/core/isofit.py", line 225, in run_set_of_spectra
    states = self.iv.invert(input_data.meas, input_data.geom)
  File "/__w/isofit/isofit/isofit/inversion/inverse.py", line 306, in invert
    prior_subset_idx = np.arange(len(x0))[self.fm.idx_surface][self.outside_ret_windows]
IndexError: boolean index did not match indexed array along dimension 0; dimension is 244 but corresponding boolean dimension is 242
```

This is a known issue from the expanded indexing due to treatment of glint but could be an issue for other surface models with other parameters.

### PR DESCRIPTION
**Pull request by unbohn**
This PR implements a separation of surface state vector indexes within the forward class to cover cases where we retrieve additional non-reflectance surface parameters, such as sun glint for water surfaces or liquid water over vegetated pixels. This also fixes #315.

### CODE REVIEW

**Comment by unbohn** [comment]
Ok, there still seems to be an issue with a non-existing class attribute. Might be the parent surface class that's missing the `idx_lamb`. I'll take a look at this tomorrow!

**Comment by unbohn** [comment]
The `AttributeError` is fixed with commit [2a39ddc](https://github.com/isofit/isofit/pull/319/commits/2a39ddc79297efdb6df7c79298f248aba48161c6).

**Comment by pgbrodrick** [comment]
This looks great and seems safe from a quick review.  I'd like to merge in #313 first, which we can hopefully address in the coming week, and will give help provide additional confirmation.

**Comment by pgbrodrick** [comment]
Let's do it!  #313 needs this in place to satisfy all checks.  Merging.

**Pull request merged**
