### PR TITLE
Heuristic water vapor first guess

### PR DESCRIPTION
**Pull request by NimrodCarmon**

### CODE REVIEW

**Comment by davidraythompson** [comment]
NB I might not call this a "fix," since the former method was an intentional choice :) Nimrod, thanks for your work on this code, and for your contribution to the repository!  
Have you double checked it does not change the behavior when running in forward simulation mode?

**Comment by NimrodCarmon** [comment]
Hi David,
Sorry for the bad words selection.
Tracing the path of the forward simulation, I do not find that the changed function is called. 
I was running the forward and inverse like this in the past few days without any problem, but let me double check again.

**Comment by NimrodCarmon** [comment]
I double checked the forward simulation, and it seems to not be affected from this change.

**Comment by davidraythompson** [comment]
No worries about wording, of course! Thanks again for your contribution.  Duly merging in your change!

**Pull request merged**
