### PR TITLE
Custom RTE Support

### PR DESCRIPTION
**Pull request by jammont**
# Description

Attempts to improve the support for creating custom radiative transfer engines by expanding the documentation

# Changes

- Moved RTEs to new `engines/` subdir
  - Added `__init__.py` to this directory for engines to be imported and matched to a config string name
- Added template files as instructions
  - `full` contains all of the functions that could be defined by a custom RTE as well as descriptions on how these functions are used
  - `minimal` the minimal structure required to be defined

### CODE REVIEW

**Comment by unbohn** [comment]
@jammont We still have some merge conflicts here. Could you resolve those first before we dive into the review of the PR?

**Comment by jammont** [comment]
This has now been rebased and integrate kernel_flows

**Comment by unbohn** [comment]
Nice work, @jammont! I ran a few local tests and all works well. From my point of view, we're good to go with this one. @pgbrodrick Please take a look and merge if affirmative.

**Review by unbohn — APPROVED** [review]

**Comment by pgbrodrick** [comment]
This looks good - thanks for adding guiding comments so folks can find the various initializations.

**Pull request merged**
